#!/bin/bash

for files in test_files/*cs306.cfg
do
	echo "Generating symtab for $files"
	./cfglp -symtab $files
done

for files in test_files/*.sym
do
	mv $files "$files"_our
done

for files in test_files/*.spim
do
	mv $files "$files"_our
done
