#!/bin/bash

# read from twitter_positive_words and positive_words and add to my_positive

cat /dev/null > my_negative

while read line
do
	if grep -Fxq $line twitter_positive_words twitter_objective_words positive_words my_negative my_negative
	then
		continue
	else
		# word not found
		echo $line >> my_negative	
	fi
done < twitter_negative_words

while read line
do
	if grep -Fxq $line twitter_positive_words twitter_objective_words positive_words my_negative
	then
		continue
	else
		# word not found
		echo $line >> my_negative
	fi
done < negative_words

