#!/bin/bash

# read from twitter_positive_words and positive_words and add to my_positive

cat /dev/null > my_objective

while read line
do
	if grep -Fxq $line twitter_negative_words twitter_positive_words positive_words negative_words my_objective
	then
		continue
	else
		# word not found
		echo $line >> my_objective	
	fi
done < twitter_objective_words
