#!/bin/bash

i=0.001

for file in $(seq 1 20)
do
file="error_vs_numIterations_with_momentum_xor${file}"
echo $file
gnuplot <<__EOF
set term png
set title 'Error v/s No. of Iterations (eta = 0.4, Momentum Factor = ${i})'
set ylabel 'Error'
set xlabel 'No. of Iterations'
set datafile separator ","
set output "${file}.png"
plot "${file}" using 1:2 smooth unique
__EOF
#i=$(($i+0.05))
i=$(echo "$i+0.05" | bc -l) 
done
